import { type Video } from "@shared/schema";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Download, Trash2, Calendar, HardDrive } from "lucide-react";
import { useDeleteVideo } from "@/hooks/use-videos";
import { format } from "date-fns";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { useState } from "react";
import { motion } from "framer-motion";

interface VideoCardProps {
  video: Video;
}

export function VideoCard({ video }: VideoCardProps) {
  const { mutate: deleteVideo, isPending: isDeleting } = useDeleteVideo();
  const [isPlaying, setIsPlaying] = useState(false);

  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.9 }}
      transition={{ duration: 0.3 }}
    >
      <Card className="group overflow-hidden bg-card border-white/5 hover:border-primary/30 transition-all duration-300 hover:shadow-2xl hover:shadow-primary/5">
        <div className="relative aspect-video bg-black/40 overflow-hidden">
          {/* 
            Ideally we would use a thumbnail here if generated by the backend.
            For now, we render the video with preload metadata.
            On hover/interaction, we could auto-play or show controls.
          */}
          <video
            src={video.url}
            className="w-full h-full object-cover"
            controls
            preload="metadata"
            onPlay={() => setIsPlaying(true)}
            onPause={() => setIsPlaying(false)}
          />
          
          {/* Overlay gradient only visible when not playing to make text legible if overlaid */}
          {!isPlaying && (
            <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
          )}
        </div>

        <div className="p-5 space-y-4">
          <div>
            <h3 className="text-xl font-bold text-white font-display leading-tight truncate" title={video.title}>
              {video.title}
            </h3>
            <div className="flex items-center gap-3 mt-2 text-xs text-muted-foreground">
              <span className="flex items-center gap-1">
                <Calendar className="w-3 h-3" />
                {video.createdAt && format(new Date(video.createdAt), 'MMM d, yyyy')}
              </span>
              <span className="flex items-center gap-1">
                <HardDrive className="w-3 h-3" />
                {(video.size / (1024 * 1024)).toFixed(1)} MB
              </span>
            </div>
          </div>

          {video.description && (
            <p className="text-sm text-muted-foreground line-clamp-2 min-h-[2.5em]">
              {video.description}
            </p>
          )}

          <div className="flex items-center justify-between pt-2 border-t border-white/5">
            <a 
              href={video.url} 
              download={video.originalName} 
              className="text-primary hover:text-primary/80 text-sm font-medium flex items-center gap-2 transition-colors"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Download className="w-4 h-4" />
              Download
            </a>

            <AlertDialog>
              <AlertDialogTrigger asChild>
                <Button 
                  variant="ghost" 
                  size="icon" 
                  className="h-8 w-8 text-muted-foreground hover:text-destructive hover:bg-destructive/10 transition-colors"
                >
                  <Trash2 className="w-4 h-4" />
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent className="bg-card border-white/10">
                <AlertDialogHeader>
                  <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
                  <AlertDialogDescription>
                    This action cannot be undone. This will permanently delete the video
                    "{video.title}" from our servers.
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel className="border-white/10 hover:bg-white/5">Cancel</AlertDialogCancel>
                  <AlertDialogAction
                    onClick={() => deleteVideo(video.id)}
                    className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                  >
                    {isDeleting ? "Deleting..." : "Delete Video"}
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          </div>
        </div>
      </Card>
    </motion.div>
  );
}
